---
title: "Explore Shiny App Active Hours"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(shiny)
library(dplyr)
library(plotly)
library(readr)
```

```{r data}
source("../R/get_latest_output.R")
latest_result <- get_latest_output("../outputs", file_prefix="apps_full_activity")
all_apps_df <- read_csv(latest_result)
all_apps_df$date <- as.Date(all_apps_df$date)
start_date <- min(all_apps_df$date)
end_date <- max(all_apps_df$date)
apps_to_plot <- as.character(unique(all_apps_df$app_name))

```

Column {.sidebar data-width=200}
-----------------------------------------------------------------------

```{r}

selectInput("app_name_select", label="Select an app:", choices=apps_to_plot)
```


Column {data-width=650}
-----------------------------------------------------------------------

### Active Hours Per Day `r start_date` to `r end_date`

```{r}
plot_data <- reactive(all_apps_df %>% filter(app_name ==input$app_name_select))
renderPlotly(plot_data() %>% plot_ly(x=~date, y=~hours, type="scatter", mode="lines"))

```


